### ISSUE TITLE
deploy-all deploys livy and livy for spark3 twice

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-getting-started#174]
This is the current state of `deploy-all.yml` playbook :
```yaml
...
- import_playbook: deploy-spark.yml
- import_playbook: deploy-livy.yml
- import_playbook: deploy-spark3.yml
- import_playbook: deploy-livy-spark3.yml
...
```
But `deploy-spark.yml` already deploys livy, and `deploy-spark3.yml` already deploys livy for spark3.  
This should be enough :
```yaml
...
- import_playbook: deploy-spark.yml
- import_playbook: deploy-spark3.yml
...
```
